# Generated by Django 3.2 on 2021-05-08 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Application', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Produits',
            new_name='Produit',
        ),
    ]
